spring:
  application:
    name: ksiegowosc

server:
  port: ${PORT:8080}

clients:
  merit:
    base-url: https://program.360ksiegowosc.pl/api/v1
    api-id: ${MERIT_API_ID:change-me}
    api-key: ${MERIT_API_KEY:change-me}
    v2-base-url: https://program.360ksiegowosc.pl/api/v2
